version: '3'
services:
    nginx:
        build:
            context: ./nginx
            args:
                NGINX_VERSION: $NGINX_VERSION
        depends_on:
            - php
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./website:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/cert:/etc/nginx/cert
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/log/error.log:/var/log/nginx/error.log
        restart: always
        container_name: nginx

    php:
        build:
            context: ./php
            args:
                PHP_VERSION: $PHP_VERSION
        volumes:
            - ./website:/var/www/html
            - ./php/config/php.ini:/usr/local/etc/php/php.ini
        restart: always
        container_name: php
